# Generated by Django 2.0.3 on 2018-03-31 10:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=40)),
                ('category', models.CharField(max_length=40, null=True)),
                ('sub_category', models.CharField(max_length=40, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=150)),
                ('area', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=40)),
                ('zipcode', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(code='LengthError', message='Length has to be 6', regex='^.{6}$')])),
                ('contact_no', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaclass', models.CharField(max_length=40)),
                ('metavalue', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('f_name', models.CharField(max_length=20)),
                ('l_name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=40)),
                ('contact_no', models.CharField(max_length=20, null=True)),
                ('address', models.CharField(max_length=10, null=True)),
                ('area', models.CharField(max_length=20, null=True)),
                ('city', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=20, null=True)),
                ('zipcode', models.DecimalField(decimal_places=0, max_digits=6)),
            ],
        ),
        migrations.AddField(
            model_name='usermeta',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.UserValidation'),
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant'),
        ),
    ]
