# Generated by Django 2.0.3 on 2018-03-31 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_no',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
