# Generated by Django 2.0.3 on 2018-03-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180331_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='contact_no',
            field=models.CharField(max_length=20),
        ),
    ]
