# Generated by Django 2.0.3 on 2018-04-01 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20180331_1736'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('extended_price', models.BigIntegerField()),
                ('order_date', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('change_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_by_user_id', to='food.UserValidation')),
            ],
        ),
        migrations.CreateModel(
            name='OrderHeader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_items', models.IntegerField()),
                ('order_value', models.FloatField()),
                ('taxes', models.FloatField()),
                ('discount', models.FloatField()),
                ('net_amount', models.BigIntegerField()),
                ('order_date', models.DateTimeField()),
                ('date_created', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('change_by_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.UserValidation')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='header_user_id', to='food.UserValidation')),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Menu'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.OrderHeader'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.Restaurant'),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_user_id', to='food.UserValidation'),
        ),
    ]
