# Generated by Django 2.0.3 on 2018-04-02 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_auto_20180401_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderheader',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='discount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='net_amount',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='number_of_items',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 11, 9, 58, 91874), null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='taxes',
            field=models.FloatField(null=True),
        ),
    ]
