# Generated by Django 2.0.3 on 2018-04-02 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180402_1109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='change_by_user_id',
            new_name='change_by_user',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='item_id',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderheader',
            old_name='change_by_user_id',
            new_name='change_by_user',
        ),
        migrations.RenameField(
            model_name='orderheader',
            old_name='restaurant_id',
            new_name='restaurant',
        ),
        migrations.RenameField(
            model_name='orderheader',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 11, 17, 3, 412824), null=True),
        ),
    ]
