# Generated by Django 2.0.3 on 2018-04-02 17:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20180402_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='date_created',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='date_modified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='orderheader',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 2, 23, 29, 55, 38870), null=True),
        ),
    ]
